# ~/.bash_logout: executed by bash(1) when login shell exits.

# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi

sleep 0.2
/usr/local/bin/relay_off.sh 20
sleep 0.2
/usr/local/bin/relay_off.sh 21
sleep 0.2
/usr/local/bin/relay_deinit.sh 20
sleep 0.2
/usr/local/bin/relay_deinit.sh 21
sleep 0.2

